parallel-jobs = 1
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"
excluded-patches = "custom-branding-icon-revancify-blue custom-package-name custom-branding-music-name"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "materialyou"
excluded-patches = "custom-branding-youtube-name custom-branding-icon-revancify-blue custom-package-name"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
build-mode = "both"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
build-mode = "both"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
build-mode = "both"
